apiVersion: v1
kind: Pod
metadata:
  name: help-keyman-com
  namespace: keyman
  labels:
    run: help-keyman-com
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - name: app-php
    image: help-keyman-website
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: help-site-app
      mountPath: /var/www/html
    readinessProbe:
      httpGet:
        path: /robots.txt
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 15
    livenessProbe:
      tcpSocket:
        port: 80
  - name: updater
    image: bitnami/git
    imagePullPolicy: IfNotPresent
    env:
    - name: UPDATE_POLL
      value: "900"
    command: ["sh", "-c"]
    args:
    - |
      cd /mnt
      git fetch && git reset --hard HEAD
      while sleep ${UPDATE_POLL}; do
        git fetch && git reset --hard HEAD
      done
    lifecycle:
      preStop:
        exec:
          command: ["/usr/bin/pkill", "sleep"]
    volumeMounts:
    - name: help-site-app
      mountPath: /mnt
  initContainers:
  - name: init-site-data
    image: bitnami/git
    imagePullPolicy: IfNotPresent
    env:
    - name: SITE_GIT_BRANCH
      value: chore/start-kubernetes
#      value: master
    command: ["sh", "-c"]
    args:
    - |
      cd /mnt
      test -d .git && exit 0
      echo Initial clone
      git clone \
        --filter=blob:none \
        --no-checkout \
        --branch=${SITE_GIT_BRANCH} \
        https://github.com/keymanapp/help.keyman.com.git ./
      echo Configure sparse-checkout
      git sparse-checkout set --no-cone \
        "/*"              \
        "!.github"        \
        "!resources"      \
        "!.editorconfig"  \
        "!composer.*"     \
        "!Dockerfile"     \
        "!Readme.md"      \
        "!web.config"
      echo Link vendored PHP
      ln -sf /var/www/vendor vendor
    volumeMounts:
    - name: help-site-app
      mountPath: /mnt
  volumes:
  - name: help-site-app
    persistentVolumeClaim:
      claimName: help-keyman-com

