#
# Automatically approves pull requests opened by keyman-server
# The initial use of this action is to upload product help documentation
# with resources/build/help-keyman-com.sh.
# That script creates a PR and then this workflow will be
# triggered to approve the PR, and then auto-merge-keyman-server-pr.yml
# will merge it
#
name: Auto Approve PRs from keyman-server

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@44888193675f29a83e04faf4002fa8c0b537b1e4 # v3.2.1
      if: github.actor == 'keyman-server'
