#
# Automatically approves pull requests opened by keyman-server
# The initial use of this action is to upload product help documentation
# with resources/build/help-keyman-com.sh.
# That script creates a PR and then this workflow will be
# triggered to approve the PR, and then auto-merge-keyman-server-pr.yml
# will merge it
#
name: Auto Approve PRs from keyman-server

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Approve pull request
      if: contains(github.event.pull_request.labels.*.name, 'auto')
      if: github.actor == 'keyman-server'
      run: |
           gh pr review --approve
    - name: Enable auto-merge
      if: contains(github.event.pull_request.labels.*.name, 'auto')
      run: |
           gh pr merge --merge --auto
